name: Print setup java env
on: workflow_dispatch
jobs:
  print-env-node:
    runs-on: ubuntu-latest
    name: Print setup java env
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Print java home env
        uses: actions/github-script@v3
        with:
          script: |
            console.log(process.env["JAVA_HOME"]);
